### ISSUE TITLE
Make the repo public

### ISSUE THREAD

**Issue by flozzone** [hrmvienna/regelungstechnik_ws16#1]
Hey @hrmvienna,

lets make this repo public? I've a collegue who asked for it.

Greets ;),
flozzone

**Comment by flozzone** [comment]
was there also a task 4?

**Comment by hrmvienna** [comment]
Repo published, hf ;)

No, just 3 (see the RegelungstechnikLU_Skript.pdf). 3 tasks were already enough I would say^^
